#
# Quick start config settings
# ===========================================
#
# These are a small subset of configuration 
# settings.
#
# See docs to access a full config.yaml file.
#

pinlabel:
  box:
    offset: [8,0]
    width: 50
    height: 24
  tag: pl

legend:
  rect:
    width: 220

#
# Tags are used to provide color to pinlabels
# and as a data source to generate a legend
#

tags:
  analog:
    title: Analog
    color: [255, 142, 116]
  gpio:
    title: GPIO
    color: [44, 91, 123]
  pwr:
    title: Power management
    color: [150, 2, 29]
  pwm:
    title: PWM
    color: [54, 157, 158]